project:
  type: book

book:
  title: "Introduction to Data Analysis"
  author: "David Gerbing"
  date: now
  date-format: "MMM D, YYYY hh:mm a"
  chapters:
    - index.qmd
    - 01-Intro.qmd
    - 02-Data.qmd
    - 03-Visualization.qmd
    - 04-MoreStuff.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    css: style.css
    callout-icon: false
  pdf:
    documentclass: scrreprt
theme:
  light: cosmo
  dark: solar
editor: visual

